// portable key mods, from SDL
// https://wiki.libsdl.org/SDL2/SDL_Keymod

use std::mem::transmute;

use crate::vendor::sdl_bindings::{SDL_KeyCode, SDL_Scancode};

pub const KMOD_NONE: u16 = 0x0000;
pub const KMOD_LSHIFT: u16 = 0x0001;
pub const KMOD_RSHIFT: u16 = 0x0002;
pub const KMOD_LCTRL: u16 = 0x0040;
pub const KMOD_RCTRL: u16 = 0x0080;
pub const KMOD_LALT: u16 = 0x0100;
pub const KMOD_RALT: u16 = 0x0200;
pub const KMOD_LGUI: u16 = 0x0400;
pub const KMOD_RGUI: u16 = 0x0800;
pub const KMOD_NUM: u16 = 0x1000;
pub const KMOD_CAPS: u16 = 0x2000;
pub const KMOD_MODE: u16 = 0x4000;
pub const KMOD_SCROLL: u16 = 0x8000;

pub const KMOD_CTRL: u16 = KMOD_LCTRL | KMOD_RCTRL;
pub const KMOD_SHIFT: u16 = KMOD_LSHIFT | KMOD_RSHIFT;
pub const KMOD_ALT: u16 = KMOD_LALT | KMOD_RALT;
pub const KMOD_GUI: u16 = KMOD_LGUI | KMOD_RGUI;

pub const KMOD_RESERVED: u16 = KMOD_SCROLL; /* "This is for source-level compatibility with SDL 2.0.0."" */

// https://www.toptal.com/developers/keycode/table
// this sucks because "This table is based on the US standard 101 keyboard, the values may vary based on a specific hardware."

// VERY IMPERFECT KEYBOARD UTILITY
pub fn decode_keyevent_code(code: &str) -> SDL_Scancode {
    match code {
        "KeyA" => SDL_Scancode::SDL_SCANCODE_A,
        "KeyB" => SDL_Scancode::SDL_SCANCODE_B,
        "KeyC" => SDL_Scancode::SDL_SCANCODE_C,
        "KeyD" => SDL_Scancode::SDL_SCANCODE_D,
        "KeyE" => SDL_Scancode::SDL_SCANCODE_E,
        "KeyF" => SDL_Scancode::SDL_SCANCODE_F,
        "KeyG" => SDL_Scancode::SDL_SCANCODE_G,
        "KeyH" => SDL_Scancode::SDL_SCANCODE_H,
        "KeyI" => SDL_Scancode::SDL_SCANCODE_I,
        "KeyJ" => SDL_Scancode::SDL_SCANCODE_J,
        "KeyK" => SDL_Scancode::SDL_SCANCODE_K,
        "KeyL" => SDL_Scancode::SDL_SCANCODE_L,
        "KeyM" => SDL_Scancode::SDL_SCANCODE_M,
        "KeyN" => SDL_Scancode::SDL_SCANCODE_N,
        "KeyO" => SDL_Scancode::SDL_SCANCODE_O,
        "KeyP" => SDL_Scancode::SDL_SCANCODE_P,
        "KeyQ" => SDL_Scancode::SDL_SCANCODE_Q,
        "KeyR" => SDL_Scancode::SDL_SCANCODE_R,
        "KeyS" => SDL_Scancode::SDL_SCANCODE_S,
        "KeyT" => SDL_Scancode::SDL_SCANCODE_T,
        "KeyU" => SDL_Scancode::SDL_SCANCODE_U,
        "KeyV" => SDL_Scancode::SDL_SCANCODE_V,
        "KeyW" => SDL_Scancode::SDL_SCANCODE_W,
        "KeyX" => SDL_Scancode::SDL_SCANCODE_X,
        "KeyY" => SDL_Scancode::SDL_SCANCODE_Y,
        "KeyZ" => SDL_Scancode::SDL_SCANCODE_Z,
        "Unidentified" => SDL_Scancode::SDL_SCANCODE_UNKNOWN,
        "Cancel" => SDL_Scancode::SDL_SCANCODE_CANCEL,
        "Backspace" => SDL_Scancode::SDL_SCANCODE_BACKSPACE,
        "Tab" => SDL_Scancode::SDL_SCANCODE_TAB,
        "NumLock" => SDL_Scancode::SDL_SCANCODE_CLEAR,
        "Enter" => SDL_Scancode::SDL_SCANCODE_RETURN, // aka enter
        "ShiftLeft" => SDL_Scancode::SDL_SCANCODE_LSHIFT,
        "ShiftRight" => SDL_Scancode::SDL_SCANCODE_RSHIFT,
        "ControlLeft" => SDL_Scancode::SDL_SCANCODE_LCTRL,
        "ControlRight" => SDL_Scancode::SDL_SCANCODE_RCTRL,
        "AltLeft" => SDL_Scancode::SDL_SCANCODE_LALT,
        "AltRight" => SDL_Scancode::SDL_SCANCODE_RALT,
        "Pause" => SDL_Scancode::SDL_SCANCODE_PAUSE,
        "CapsLock" => SDL_Scancode::SDL_SCANCODE_CAPSLOCK,
        // Lang1 and Lang2 ommited
        "Escape" => SDL_Scancode::SDL_SCANCODE_ESCAPE,
        "Space" => SDL_Scancode::SDL_SCANCODE_SPACE,
        "PageUp" => SDL_Scancode::SDL_SCANCODE_PAGEUP,
        "PageDown" => SDL_Scancode::SDL_SCANCODE_PAGEDOWN,
        "End" => SDL_Scancode::SDL_SCANCODE_END,
        "Home" => SDL_Scancode::SDL_SCANCODE_HOME,
        "ArrowLeft" => SDL_Scancode::SDL_SCANCODE_LEFT,
        "ArrowRight" => SDL_Scancode::SDL_SCANCODE_RIGHT,
        "ArrowUp" => SDL_Scancode::SDL_SCANCODE_UP,
        "ArrowDown" => SDL_Scancode::SDL_SCANCODE_DOWN,
        "F13" => SDL_Scancode::SDL_SCANCODE_F13, // this exists?
        "Numpad0" => SDL_Scancode::SDL_SCANCODE_KP_0,
        "NumpadDecimal" => SDL_Scancode::SDL_SCANCODE_DELETE,
        "Digit0" => SDL_Scancode::SDL_SCANCODE_0,
        "Digit1" => SDL_Scancode::SDL_SCANCODE_1,
        "Digit2" => SDL_Scancode::SDL_SCANCODE_2,
        "Digit3" => SDL_Scancode::SDL_SCANCODE_3,
        "Digit4" => SDL_Scancode::SDL_SCANCODE_4,
        "Digit5" => SDL_Scancode::SDL_SCANCODE_5,
        "Digit6" => SDL_Scancode::SDL_SCANCODE_6,
        "Digit7" => SDL_Scancode::SDL_SCANCODE_7,
        "Digit8" => SDL_Scancode::SDL_SCANCODE_8,
        "Digit9" => SDL_Scancode::SDL_SCANCODE_9,
        "Period" => SDL_Scancode::SDL_SCANCODE_PERIOD,
        "Comma" => SDL_Scancode::SDL_SCANCODE_COMMA,
        "Slash" => SDL_Scancode::SDL_SCANCODE_SLASH,
        "Semicolon" => SDL_Scancode::SDL_SCANCODE_SEMICOLON,
        "Quote" => SDL_Scancode::SDL_SCANCODE_APOSTROPHE,
        "LeftBracket" => SDL_Scancode::SDL_SCANCODE_LEFTBRACKET,
        "Backslash" => SDL_Scancode::SDL_SCANCODE_BACKSLASH,
        "RightBracket" => SDL_Scancode::SDL_SCANCODE_RIGHTBRACKET,
        // will add is more people complain

        _ => SDL_Scancode::SDL_SCANCODE_UNKNOWN
    }
}

pub fn decode_keyevent_code_int(code: &str) -> u32 {
    decode_keyevent_code(code) as u32
}

pub fn decode_keyevent_key(key: &str) -> SDL_KeyCode {
    match key {
        "a" => SDL_KeyCode::SDLK_a,
        "b" => SDL_KeyCode::SDLK_b,
        "c" => SDL_KeyCode::SDLK_c,
        "d" => SDL_KeyCode::SDLK_d,
        "e" => SDL_KeyCode::SDLK_e,
        "f" => SDL_KeyCode::SDLK_f,
        "g" => SDL_KeyCode::SDLK_g,
        "h" => SDL_KeyCode::SDLK_h,
        "i" => SDL_KeyCode::SDLK_i,
        "j" => SDL_KeyCode::SDLK_j,
        "k" => SDL_KeyCode::SDLK_k,
        "l" => SDL_KeyCode::SDLK_l,
        "m" => SDL_KeyCode::SDLK_m,
        "n" => SDL_KeyCode::SDLK_n,
        "o" => SDL_KeyCode::SDLK_o,
        "p" => SDL_KeyCode::SDLK_p,
        "q" => SDL_KeyCode::SDLK_q,
        "r" => SDL_KeyCode::SDLK_r,
        "s" => SDL_KeyCode::SDLK_s,
        "t" => SDL_KeyCode::SDLK_t,
        "u" => SDL_KeyCode::SDLK_u,
        "v" => SDL_KeyCode::SDLK_v,
        "w" => SDL_KeyCode::SDLK_w,
        "x" => SDL_KeyCode::SDLK_x,
        "y" => SDL_KeyCode::SDLK_y,
        "z" => SDL_KeyCode::SDLK_z,
        "1" => SDL_KeyCode::SDLK_1,
        "2" => SDL_KeyCode::SDLK_2,
        "3" => SDL_KeyCode::SDLK_3,
        "4" => SDL_KeyCode::SDLK_4,
        "5" => SDL_KeyCode::SDLK_5,
        "6" => SDL_KeyCode::SDLK_6,
        "7" => SDL_KeyCode::SDLK_7,
        "8" => SDL_KeyCode::SDLK_8,
        "9" => SDL_KeyCode::SDLK_9,
        "0" => SDL_KeyCode::SDLK_0,
        "\n" => SDL_KeyCode::SDLK_RETURN,
        " " => SDL_KeyCode::SDLK_SPACE,
        "-" => SDL_KeyCode::SDLK_MINUS,
        "=" => SDL_KeyCode::SDLK_EQUALS,
        "ArrowUp" => SDL_KeyCode::SDLK_UP,
        "ArrowDown" => SDL_KeyCode::SDLK_DOWN,
        "ArrowLeft" => SDL_KeyCode::SDLK_LEFT,
        "ArrowRight" => SDL_KeyCode::SDLK_RIGHT,
        "Backspace" => SDL_KeyCode::SDLK_BACKSPACE,
        "Tab" => SDL_KeyCode::SDLK_TAB,
        "Control" => SDL_KeyCode::SDLK_LCTRL, // TODO: this is a hack
        "Shift" => SDL_KeyCode::SDLK_LSHIFT, // TODO: this is a hack
        "Alt" => SDL_KeyCode::SDLK_LALT, // TODO: this is a hack
        "Escape" => SDL_KeyCode::SDLK_ESCAPE,
        "Space" => SDL_KeyCode::SDLK_SPACE,
        "CapsLock" => SDL_KeyCode::SDLK_CAPSLOCK,
        _ => SDL_KeyCode::SDLK_UNKNOWN
    }
}

pub fn decode_keyevent_key_int(code: &str) -> u32 {
    decode_keyevent_key(code) as u32
}

pub fn map_keycode_to_scancode(code: SDL_KeyCode) -> SDL_Scancode {
    match code {
        SDL_KeyCode::SDLK_a => SDL_Scancode::SDL_SCANCODE_A,
        SDL_KeyCode::SDLK_b => SDL_Scancode::SDL_SCANCODE_B,
        SDL_KeyCode::SDLK_c => SDL_Scancode::SDL_SCANCODE_C,
        SDL_KeyCode::SDLK_d => SDL_Scancode::SDL_SCANCODE_D,
        SDL_KeyCode::SDLK_e => SDL_Scancode::SDL_SCANCODE_E,
        SDL_KeyCode::SDLK_f => SDL_Scancode::SDL_SCANCODE_F,
        SDL_KeyCode::SDLK_g => SDL_Scancode::SDL_SCANCODE_G,
        SDL_KeyCode::SDLK_h => SDL_Scancode::SDL_SCANCODE_H,
        SDL_KeyCode::SDLK_i => SDL_Scancode::SDL_SCANCODE_I,
        SDL_KeyCode::SDLK_j => SDL_Scancode::SDL_SCANCODE_J,
        SDL_KeyCode::SDLK_k => SDL_Scancode::SDL_SCANCODE_K,
        SDL_KeyCode::SDLK_l => SDL_Scancode::SDL_SCANCODE_L,
        SDL_KeyCode::SDLK_m => SDL_Scancode::SDL_SCANCODE_M,
        SDL_KeyCode::SDLK_n => SDL_Scancode::SDL_SCANCODE_N,
        SDL_KeyCode::SDLK_o => SDL_Scancode::SDL_SCANCODE_O,
        SDL_KeyCode::SDLK_p => SDL_Scancode::SDL_SCANCODE_P,
        SDL_KeyCode::SDLK_q => SDL_Scancode::SDL_SCANCODE_Q,
        SDL_KeyCode::SDLK_r => SDL_Scancode::SDL_SCANCODE_R,
        SDL_KeyCode::SDLK_s => SDL_Scancode::SDL_SCANCODE_S,
        SDL_KeyCode::SDLK_t => SDL_Scancode::SDL_SCANCODE_T,
        SDL_KeyCode::SDLK_u => SDL_Scancode::SDL_SCANCODE_U,
        SDL_KeyCode::SDLK_v => SDL_Scancode::SDL_SCANCODE_V,
        SDL_KeyCode::SDLK_w => SDL_Scancode::SDL_SCANCODE_W,
        SDL_KeyCode::SDLK_x => SDL_Scancode::SDL_SCANCODE_X,
        SDL_KeyCode::SDLK_y => SDL_Scancode::SDL_SCANCODE_Y,
        SDL_KeyCode::SDLK_z => SDL_Scancode::SDL_SCANCODE_Z,
        SDL_KeyCode::SDLK_1 => SDL_Scancode::SDL_SCANCODE_1,
        SDL_KeyCode::SDLK_2 => SDL_Scancode::SDL_SCANCODE_2,
        SDL_KeyCode::SDLK_3 => SDL_Scancode::SDL_SCANCODE_3,
        SDL_KeyCode::SDLK_4 => SDL_Scancode::SDL_SCANCODE_4,
        SDL_KeyCode::SDLK_5 => SDL_Scancode::SDL_SCANCODE_5,
        SDL_KeyCode::SDLK_6 => SDL_Scancode::SDL_SCANCODE_6,
        SDL_KeyCode::SDLK_7 => SDL_Scancode::SDL_SCANCODE_7,
        SDL_KeyCode::SDLK_8 => SDL_Scancode::SDL_SCANCODE_8,
        SDL_KeyCode::SDLK_9 => SDL_Scancode::SDL_SCANCODE_9,
        SDL_KeyCode::SDLK_0 => SDL_Scancode::SDL_SCANCODE_0,
        SDL_KeyCode::SDLK_RETURN => SDL_Scancode::SDL_SCANCODE_RETURN,
        SDL_KeyCode::SDLK_SPACE => SDL_Scancode::SDL_SCANCODE_SPACE,
        SDL_KeyCode::SDLK_MINUS => SDL_Scancode::SDL_SCANCODE_MINUS,
        SDL_KeyCode::SDLK_EQUALS => SDL_Scancode::SDL_SCANCODE_EQUALS,
        SDL_KeyCode::SDLK_BACKSPACE => SDL_Scancode::SDL_SCANCODE_BACKSPACE,
        SDL_KeyCode::SDLK_TAB => SDL_Scancode::SDL_SCANCODE_TAB,
        SDL_KeyCode::SDLK_LSHIFT => SDL_Scancode::SDL_SCANCODE_LSHIFT,
        SDL_KeyCode::SDLK_RSHIFT => SDL_Scancode::SDL_SCANCODE_RSHIFT,
        SDL_KeyCode::SDLK_LCTRL => SDL_Scancode::SDL_SCANCODE_LCTRL,
        SDL_KeyCode::SDLK_RCTRL => SDL_Scancode::SDL_SCANCODE_RCTRL,
        SDL_KeyCode::SDLK_LALT => SDL_Scancode::SDL_SCANCODE_LALT,
        SDL_KeyCode::SDLK_RALT => SDL_Scancode::SDL_SCANCODE_RALT,
        SDL_KeyCode::SDLK_LGUI => SDL_Scancode::SDL_SCANCODE_LGUI,
        SDL_KeyCode::SDLK_RGUI => SDL_Scancode::SDL_SCANCODE_RGUI,
        SDL_KeyCode::SDLK_CAPSLOCK => SDL_Scancode::SDL_SCANCODE_CAPSLOCK,
        SDL_KeyCode::SDLK_F1 => SDL_Scancode::SDL_SCANCODE_F1,
        SDL_KeyCode::SDLK_F2 => SDL_Scancode::SDL_SCANCODE_F2,
        SDL_KeyCode::SDLK_F3 => SDL_Scancode::SDL_SCANCODE_F3,
        SDL_KeyCode::SDLK_F4 => SDL_Scancode::SDL_SCANCODE_F4,
        SDL_KeyCode::SDLK_F5 => SDL_Scancode::SDL_SCANCODE_F5,
        SDL_KeyCode::SDLK_F6 => SDL_Scancode::SDL_SCANCODE_F6,
        SDL_KeyCode::SDLK_F7 => SDL_Scancode::SDL_SCANCODE_F7,
        SDL_KeyCode::SDLK_F8 => SDL_Scancode::SDL_SCANCODE_F8,
        SDL_KeyCode::SDLK_F9 => SDL_Scancode::SDL_SCANCODE_F9,
        SDL_KeyCode::SDLK_F10 => SDL_Scancode::SDL_SCANCODE_F10,
        SDL_KeyCode::SDLK_F11 => SDL_Scancode::SDL_SCANCODE_F11,
        SDL_KeyCode::SDLK_F12 => SDL_Scancode::SDL_SCANCODE_F12,
        SDL_KeyCode::SDLK_PRINTSCREEN => SDL_Scancode::SDL_SCANCODE_PRINTSCREEN,
        SDL_KeyCode::SDLK_ESCAPE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_EXCLAIM => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_QUOTEDBL => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_HASH => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_PERCENT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_DOLLAR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AMPERSAND => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_QUOTE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_LEFTPAREN => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_RIGHTPAREN => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_ASTERISK => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_PLUS => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_COMMA => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_PERIOD => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_SLASH => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_COLON => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_SEMICOLON => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_LESS => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_GREATER => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_QUESTION => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_LEFTBRACKET => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_BACKSLASH => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_RIGHTBRACKET => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_CARET => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_UNDERSCORE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_BACKQUOTE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_SCROLLLOCK => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_PAUSE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_INSERT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_HOME => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_PAGEUP => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_DELETE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_END => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_PAGEDOWN => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_RIGHT => SDL_Scancode::SDL_SCANCODE_RIGHT,
        SDL_KeyCode::SDLK_LEFT => SDL_Scancode::SDL_SCANCODE_LEFT,
        SDL_KeyCode::SDLK_DOWN => SDL_Scancode::SDL_SCANCODE_DOWN,
        SDL_KeyCode::SDLK_UP => SDL_Scancode::SDL_SCANCODE_UP,
        SDL_KeyCode::SDLK_NUMLOCKCLEAR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_DIVIDE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_MULTIPLY => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_MINUS => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_PLUS => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_ENTER => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_1 => SDL_Scancode::SDL_SCANCODE_KP_1,
        SDL_KeyCode::SDLK_KP_2 => SDL_Scancode::SDL_SCANCODE_KP_2,
        SDL_KeyCode::SDLK_KP_3 => SDL_Scancode::SDL_SCANCODE_KP_3,
        SDL_KeyCode::SDLK_KP_4 => SDL_Scancode::SDL_SCANCODE_KP_4,
        SDL_KeyCode::SDLK_KP_5 => SDL_Scancode::SDL_SCANCODE_KP_5,
        SDL_KeyCode::SDLK_KP_6 => SDL_Scancode::SDL_SCANCODE_KP_6,
        SDL_KeyCode::SDLK_KP_7 => SDL_Scancode::SDL_SCANCODE_KP_7,
        SDL_KeyCode::SDLK_KP_8 => SDL_Scancode::SDL_SCANCODE_KP_8,
        SDL_KeyCode::SDLK_KP_9 => SDL_Scancode::SDL_SCANCODE_KP_9,
        SDL_KeyCode::SDLK_KP_0 => SDL_Scancode::SDL_SCANCODE_KP_0,
        SDL_KeyCode::SDLK_KP_PERIOD => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_APPLICATION => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_POWER => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_EQUALS => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F13 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F14 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F15 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F16 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F17 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F18 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F19 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F20 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F21 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F22 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F23 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_F24 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_EXECUTE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_HELP => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_MENU => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_SELECT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_STOP => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AGAIN => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_UNDO => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_CUT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_COPY => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_PASTE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_FIND => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_MUTE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_VOLUMEUP => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_VOLUMEDOWN => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_COMMA => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_EQUALSAS400 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_ALTERASE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_SYSREQ => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_CANCEL => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_CLEAR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_PRIOR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_RETURN2 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_SEPARATOR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_OUT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_OPER => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_CLEARAGAIN => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_CRSEL => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_EXSEL => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_00 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_000 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_THOUSANDSSEPARATOR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_DECIMALSEPARATOR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_CURRENCYUNIT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_CURRENCYSUBUNIT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_LEFTPAREN => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_RIGHTPAREN => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_LEFTBRACE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_RIGHTBRACE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_TAB => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_BACKSPACE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_A => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_B => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_C => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_D => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_E => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_F => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_XOR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_POWER => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_PERCENT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_LESS => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_GREATER => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_AMPERSAND => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_DBLAMPERSAND => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_VERTICALBAR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_DBLVERTICALBAR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_COLON => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_HASH => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_SPACE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_AT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_EXCLAM => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_MEMSTORE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_MEMRECALL => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_MEMCLEAR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_MEMADD => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_MEMSUBTRACT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_MEMMULTIPLY => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_MEMDIVIDE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_PLUSMINUS => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_CLEAR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_CLEARENTRY => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_BINARY => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_OCTAL => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_DECIMAL => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KP_HEXADECIMAL => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_MODE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AUDIONEXT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AUDIOPREV => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AUDIOSTOP => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AUDIOPLAY => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AUDIOMUTE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_MEDIASELECT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_WWW => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_MAIL => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_CALCULATOR => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_COMPUTER => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AC_SEARCH => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AC_HOME => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AC_BACK => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AC_FORWARD => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AC_STOP => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AC_REFRESH => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AC_BOOKMARKS => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_BRIGHTNESSDOWN => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_BRIGHTNESSUP => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_DISPLAYSWITCH => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KBDILLUMTOGGLE => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KBDILLUMDOWN => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_KBDILLUMUP => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_EJECT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_SLEEP => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_APP1 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_APP2 => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AUDIOREWIND => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_AUDIOFASTFORWARD => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_SOFTLEFT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_SOFTRIGHT => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_CALL => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_ENDCALL => SDL_Scancode::SDL_SCANCODE_UNKNOWN, // TODO
        SDL_KeyCode::SDLK_UNKNOWN => SDL_Scancode::SDL_SCANCODE_UNKNOWN,
    }
}

pub fn get_sdl_keycode(key: u32) -> SDL_KeyCode {
    match key {
        0 => SDL_KeyCode::SDLK_UNKNOWN,
        13 => SDL_KeyCode::SDLK_RETURN,
        27 => SDL_KeyCode::SDLK_ESCAPE,
        8 => SDL_KeyCode::SDLK_BACKSPACE,
        9 => SDL_KeyCode::SDLK_TAB,
        32 => SDL_KeyCode::SDLK_SPACE,
        33 => SDL_KeyCode::SDLK_EXCLAIM,
        34 => SDL_KeyCode::SDLK_QUOTEDBL,
        35 => SDL_KeyCode::SDLK_HASH,
        37 => SDL_KeyCode::SDLK_PERCENT,
        36 => SDL_KeyCode::SDLK_DOLLAR,
        38 => SDL_KeyCode::SDLK_AMPERSAND,
        39 => SDL_KeyCode::SDLK_QUOTE,
        40 => SDL_KeyCode::SDLK_LEFTPAREN,
        41 => SDL_KeyCode::SDLK_RIGHTPAREN,
        42 => SDL_KeyCode::SDLK_ASTERISK,
        43 => SDL_KeyCode::SDLK_PLUS,
        44 => SDL_KeyCode::SDLK_COMMA,
        45 => SDL_KeyCode::SDLK_MINUS,
        46 => SDL_KeyCode::SDLK_PERIOD,
        47 => SDL_KeyCode::SDLK_SLASH,
        48 => SDL_KeyCode::SDLK_0,
        49 => SDL_KeyCode::SDLK_1,
        50 => SDL_KeyCode::SDLK_2,
        51 => SDL_KeyCode::SDLK_3,
        52 => SDL_KeyCode::SDLK_4,
        53 => SDL_KeyCode::SDLK_5,
        54 => SDL_KeyCode::SDLK_6,
        55 => SDL_KeyCode::SDLK_7,
        56 => SDL_KeyCode::SDLK_8,
        57 => SDL_KeyCode::SDLK_9,
        58 => SDL_KeyCode::SDLK_COLON,
        59 => SDL_KeyCode::SDLK_SEMICOLON,
        60 => SDL_KeyCode::SDLK_LESS,
        61 => SDL_KeyCode::SDLK_EQUALS,
        62 => SDL_KeyCode::SDLK_GREATER,
        63 => SDL_KeyCode::SDLK_QUESTION,
        64 => SDL_KeyCode::SDLK_AT,
        91 => SDL_KeyCode::SDLK_LEFTBRACKET,
        92 => SDL_KeyCode::SDLK_BACKSLASH,
        93 => SDL_KeyCode::SDLK_RIGHTBRACKET,
        94 => SDL_KeyCode::SDLK_CARET,
        95 => SDL_KeyCode::SDLK_UNDERSCORE,
        96 => SDL_KeyCode::SDLK_BACKQUOTE,
        97 => SDL_KeyCode::SDLK_a,
        98 => SDL_KeyCode::SDLK_b,
        99 => SDL_KeyCode::SDLK_c,
        100 => SDL_KeyCode::SDLK_d,
        101 => SDL_KeyCode::SDLK_e,
        102 => SDL_KeyCode::SDLK_f,
        103 => SDL_KeyCode::SDLK_g,
        104 => SDL_KeyCode::SDLK_h,
        105 => SDL_KeyCode::SDLK_i,
        106 => SDL_KeyCode::SDLK_j,
        107 => SDL_KeyCode::SDLK_k,
        108 => SDL_KeyCode::SDLK_l,
        109 => SDL_KeyCode::SDLK_m,
        110 => SDL_KeyCode::SDLK_n,
        111 => SDL_KeyCode::SDLK_o,
        112 => SDL_KeyCode::SDLK_p,
        113 => SDL_KeyCode::SDLK_q,
        114 => SDL_KeyCode::SDLK_r,
        115 => SDL_KeyCode::SDLK_s,
        116 => SDL_KeyCode::SDLK_t,
        117 => SDL_KeyCode::SDLK_u,
        118 => SDL_KeyCode::SDLK_v,
        119 => SDL_KeyCode::SDLK_w,
        120 => SDL_KeyCode::SDLK_x,
        121 => SDL_KeyCode::SDLK_y,
        122 => SDL_KeyCode::SDLK_z,
        1073741881 => SDL_KeyCode::SDLK_CAPSLOCK,
        1073741882 => SDL_KeyCode::SDLK_F1,
        1073741883 => SDL_KeyCode::SDLK_F2,
        1073741884 => SDL_KeyCode::SDLK_F3,
        1073741885 => SDL_KeyCode::SDLK_F4,
        1073741886 => SDL_KeyCode::SDLK_F5,
        1073741887 => SDL_KeyCode::SDLK_F6,
        1073741888 => SDL_KeyCode::SDLK_F7,
        1073741889 => SDL_KeyCode::SDLK_F8,
        1073741890 => SDL_KeyCode::SDLK_F9,
        1073741891 => SDL_KeyCode::SDLK_F10,
        1073741892 => SDL_KeyCode::SDLK_F11,
        1073741893 => SDL_KeyCode::SDLK_F12,
        1073741894 => SDL_KeyCode::SDLK_PRINTSCREEN,
        1073741895 => SDL_KeyCode::SDLK_SCROLLLOCK,
        1073741896 => SDL_KeyCode::SDLK_PAUSE,
        1073741897 => SDL_KeyCode::SDLK_INSERT,
        1073741898 => SDL_KeyCode::SDLK_HOME,
        1073741899 => SDL_KeyCode::SDLK_PAGEUP,
        127 => SDL_KeyCode::SDLK_DELETE,
        1073741901 => SDL_KeyCode::SDLK_END,
        1073741902 => SDL_KeyCode::SDLK_PAGEDOWN,
        1073741903 => SDL_KeyCode::SDLK_RIGHT,
        1073741904 => SDL_KeyCode::SDLK_LEFT,
        1073741905 => SDL_KeyCode::SDLK_DOWN,
        1073741906 => SDL_KeyCode::SDLK_UP,
        1073741907 => SDL_KeyCode::SDLK_NUMLOCKCLEAR,
        1073741908 => SDL_KeyCode::SDLK_KP_DIVIDE,
        1073741909 => SDL_KeyCode::SDLK_KP_MULTIPLY,
        1073741910 => SDL_KeyCode::SDLK_KP_MINUS,
        1073741911 => SDL_KeyCode::SDLK_KP_PLUS,
        1073741912 => SDL_KeyCode::SDLK_KP_ENTER,
        1073741913 => SDL_KeyCode::SDLK_KP_1,
        1073741914 => SDL_KeyCode::SDLK_KP_2,
        1073741915 => SDL_KeyCode::SDLK_KP_3,
        1073741916 => SDL_KeyCode::SDLK_KP_4,
        1073741917 => SDL_KeyCode::SDLK_KP_5,
        1073741918 => SDL_KeyCode::SDLK_KP_6,
        1073741919 => SDL_KeyCode::SDLK_KP_7,
        1073741920 => SDL_KeyCode::SDLK_KP_8,
        1073741921 => SDL_KeyCode::SDLK_KP_9,
        1073741922 => SDL_KeyCode::SDLK_KP_0,
        1073741923 => SDL_KeyCode::SDLK_KP_PERIOD,
        1073741925 => SDL_KeyCode::SDLK_APPLICATION,
        1073741926 => SDL_KeyCode::SDLK_POWER,
        1073741927 => SDL_KeyCode::SDLK_KP_EQUALS,
        1073741928 => SDL_KeyCode::SDLK_F13,
        1073741929 => SDL_KeyCode::SDLK_F14,
        1073741930 => SDL_KeyCode::SDLK_F15,
        1073741931 => SDL_KeyCode::SDLK_F16,
        1073741932 => SDL_KeyCode::SDLK_F17,
        1073741933 => SDL_KeyCode::SDLK_F18,
        1073741934 => SDL_KeyCode::SDLK_F19,
        1073741935 => SDL_KeyCode::SDLK_F20,
        1073741936 => SDL_KeyCode::SDLK_F21,
        1073741937 => SDL_KeyCode::SDLK_F22,
        1073741938 => SDL_KeyCode::SDLK_F23,
        1073741939 => SDL_KeyCode::SDLK_F24,
        1073741940 => SDL_KeyCode::SDLK_EXECUTE,
        1073741941 => SDL_KeyCode::SDLK_HELP,
        1073741942 => SDL_KeyCode::SDLK_MENU,
        1073741943 => SDL_KeyCode::SDLK_SELECT,
        1073741944 => SDL_KeyCode::SDLK_STOP,
        1073741945 => SDL_KeyCode::SDLK_AGAIN,
        1073741946 => SDL_KeyCode::SDLK_UNDO,
        1073741947 => SDL_KeyCode::SDLK_CUT,
        1073741948 => SDL_KeyCode::SDLK_COPY,
        1073741949 => SDL_KeyCode::SDLK_PASTE,
        1073741950 => SDL_KeyCode::SDLK_FIND,
        1073741951 => SDL_KeyCode::SDLK_MUTE,
        1073741952 => SDL_KeyCode::SDLK_VOLUMEUP,
        1073741953 => SDL_KeyCode::SDLK_VOLUMEDOWN,
        1073741957 => SDL_KeyCode::SDLK_KP_COMMA,
        1073741958 => SDL_KeyCode::SDLK_KP_EQUALSAS400,
        1073741977 => SDL_KeyCode::SDLK_ALTERASE,
        1073741978 => SDL_KeyCode::SDLK_SYSREQ,
        1073741979 => SDL_KeyCode::SDLK_CANCEL,
        1073741980 => SDL_KeyCode::SDLK_CLEAR,
        1073741981 => SDL_KeyCode::SDLK_PRIOR,
        1073741982 => SDL_KeyCode::SDLK_RETURN2,
        1073741983 => SDL_KeyCode::SDLK_SEPARATOR,
        1073741984 => SDL_KeyCode::SDLK_OUT,
        1073741985 => SDL_KeyCode::SDLK_OPER,
        1073741986 => SDL_KeyCode::SDLK_CLEARAGAIN,
        1073741987 => SDL_KeyCode::SDLK_CRSEL,
        1073741988 => SDL_KeyCode::SDLK_EXSEL,
        1073742000 => SDL_KeyCode::SDLK_KP_00,
        1073742001 => SDL_KeyCode::SDLK_KP_000,
        1073742002 => SDL_KeyCode::SDLK_THOUSANDSSEPARATOR,
        1073742003 => SDL_KeyCode::SDLK_DECIMALSEPARATOR,
        1073742004 => SDL_KeyCode::SDLK_CURRENCYUNIT,
        1073742005 => SDL_KeyCode::SDLK_CURRENCYSUBUNIT,
        1073742006 => SDL_KeyCode::SDLK_KP_LEFTPAREN,
        1073742007 => SDL_KeyCode::SDLK_KP_RIGHTPAREN,
        1073742008 => SDL_KeyCode::SDLK_KP_LEFTBRACE,
        1073742009 => SDL_KeyCode::SDLK_KP_RIGHTBRACE,
        1073742010 => SDL_KeyCode::SDLK_KP_TAB,
        1073742011 => SDL_KeyCode::SDLK_KP_BACKSPACE,
        1073742012 => SDL_KeyCode::SDLK_KP_A,
        1073742013 => SDL_KeyCode::SDLK_KP_B,
        1073742014 => SDL_KeyCode::SDLK_KP_C,
        1073742015 => SDL_KeyCode::SDLK_KP_D,
        1073742016 => SDL_KeyCode::SDLK_KP_E,
        1073742017 => SDL_KeyCode::SDLK_KP_F,
        1073742018 => SDL_KeyCode::SDLK_KP_XOR,
        1073742019 => SDL_KeyCode::SDLK_KP_POWER,
        1073742020 => SDL_KeyCode::SDLK_KP_PERCENT,
        1073742021 => SDL_KeyCode::SDLK_KP_LESS,
        1073742022 => SDL_KeyCode::SDLK_KP_GREATER,
        1073742023 => SDL_KeyCode::SDLK_KP_AMPERSAND,
        1073742024 => SDL_KeyCode::SDLK_KP_DBLAMPERSAND,
        1073742025 => SDL_KeyCode::SDLK_KP_VERTICALBAR,
        1073742026 => SDL_KeyCode::SDLK_KP_DBLVERTICALBAR,
        1073742027 => SDL_KeyCode::SDLK_KP_COLON,
        1073742028 => SDL_KeyCode::SDLK_KP_HASH,
        1073742029 => SDL_KeyCode::SDLK_KP_SPACE,
        1073742030 => SDL_KeyCode::SDLK_KP_AT,
        1073742031 => SDL_KeyCode::SDLK_KP_EXCLAM,
        1073742032 => SDL_KeyCode::SDLK_KP_MEMSTORE,
        1073742033 => SDL_KeyCode::SDLK_KP_MEMRECALL,
        1073742034 => SDL_KeyCode::SDLK_KP_MEMCLEAR,
        1073742035 => SDL_KeyCode::SDLK_KP_MEMADD,
        1073742036 => SDL_KeyCode::SDLK_KP_MEMSUBTRACT,
        1073742037 => SDL_KeyCode::SDLK_KP_MEMMULTIPLY,
        1073742038 => SDL_KeyCode::SDLK_KP_MEMDIVIDE,
        1073742039 => SDL_KeyCode::SDLK_KP_PLUSMINUS,
        1073742040 => SDL_KeyCode::SDLK_KP_CLEAR,
        1073742041 => SDL_KeyCode::SDLK_KP_CLEARENTRY,
        1073742042 => SDL_KeyCode::SDLK_KP_BINARY,
        1073742043 => SDL_KeyCode::SDLK_KP_OCTAL,
        1073742044 => SDL_KeyCode::SDLK_KP_DECIMAL,
        1073742045 => SDL_KeyCode::SDLK_KP_HEXADECIMAL,
        1073742048 => SDL_KeyCode::SDLK_LCTRL,
        1073742049 => SDL_KeyCode::SDLK_LSHIFT,
        1073742050 => SDL_KeyCode::SDLK_LALT,
        1073742051 => SDL_KeyCode::SDLK_LGUI,
        1073742052 => SDL_KeyCode::SDLK_RCTRL,
        1073742053 => SDL_KeyCode::SDLK_RSHIFT,
        1073742054 => SDL_KeyCode::SDLK_RALT,
        1073742055 => SDL_KeyCode::SDLK_RGUI,
        1073742081 => SDL_KeyCode::SDLK_MODE,
        1073742082 => SDL_KeyCode::SDLK_AUDIONEXT,
        1073742083 => SDL_KeyCode::SDLK_AUDIOPREV,
        1073742084 => SDL_KeyCode::SDLK_AUDIOSTOP,
        1073742085 => SDL_KeyCode::SDLK_AUDIOPLAY,
        1073742086 => SDL_KeyCode::SDLK_AUDIOMUTE,
        1073742087 => SDL_KeyCode::SDLK_MEDIASELECT,
        1073742088 => SDL_KeyCode::SDLK_WWW,
        1073742089 => SDL_KeyCode::SDLK_MAIL,
        1073742090 => SDL_KeyCode::SDLK_CALCULATOR,
        1073742091 => SDL_KeyCode::SDLK_COMPUTER,
        1073742092 => SDL_KeyCode::SDLK_AC_SEARCH,
        1073742093 => SDL_KeyCode::SDLK_AC_HOME,
        1073742094 => SDL_KeyCode::SDLK_AC_BACK,
        1073742095 => SDL_KeyCode::SDLK_AC_FORWARD,
        1073742096 => SDL_KeyCode::SDLK_AC_STOP,
        1073742097 => SDL_KeyCode::SDLK_AC_REFRESH,
        1073742098 => SDL_KeyCode::SDLK_AC_BOOKMARKS,
        1073742099 => SDL_KeyCode::SDLK_BRIGHTNESSDOWN,
        1073742100 => SDL_KeyCode::SDLK_BRIGHTNESSUP,
        1073742101 => SDL_KeyCode::SDLK_DISPLAYSWITCH,
        1073742102 => SDL_KeyCode::SDLK_KBDILLUMTOGGLE,
        1073742103 => SDL_KeyCode::SDLK_KBDILLUMDOWN,
        1073742104 => SDL_KeyCode::SDLK_KBDILLUMUP,
        1073742105 => SDL_KeyCode::SDLK_EJECT,
        1073742106 => SDL_KeyCode::SDLK_SLEEP,
        1073742107 => SDL_KeyCode::SDLK_APP1,
        1073742108 => SDL_KeyCode::SDLK_APP2,
        1073742109 => SDL_KeyCode::SDLK_AUDIOREWIND,
        1073742110 => SDL_KeyCode::SDLK_AUDIOFASTFORWARD,
        1073742111 => SDL_KeyCode::SDLK_SOFTLEFT,
        1073742112 => SDL_KeyCode::SDLK_SOFTRIGHT,
        1073742113 => SDL_KeyCode::SDLK_CALL,
        1073742114 => SDL_KeyCode::SDLK_ENDCALL,
        _ => SDL_KeyCode::SDLK_UNKNOWN,
    }
}

pub fn get_sdl_scancode(code: u32) -> SDL_Scancode {
    match code {
        0 => SDL_Scancode::SDL_SCANCODE_UNKNOWN,
        4 => SDL_Scancode::SDL_SCANCODE_A,
        5 => SDL_Scancode::SDL_SCANCODE_B,
        6 => SDL_Scancode::SDL_SCANCODE_C,
        7 => SDL_Scancode::SDL_SCANCODE_D,
        8 => SDL_Scancode::SDL_SCANCODE_E,
        9 => SDL_Scancode::SDL_SCANCODE_F,
        10 => SDL_Scancode::SDL_SCANCODE_G,
        11 => SDL_Scancode::SDL_SCANCODE_H,
        12 => SDL_Scancode::SDL_SCANCODE_I,
        13 => SDL_Scancode::SDL_SCANCODE_J,
        14 => SDL_Scancode::SDL_SCANCODE_K,
        15 => SDL_Scancode::SDL_SCANCODE_L,
        16 => SDL_Scancode::SDL_SCANCODE_M,
        17 => SDL_Scancode::SDL_SCANCODE_N,
        18 => SDL_Scancode::SDL_SCANCODE_O,
        19 => SDL_Scancode::SDL_SCANCODE_P,
        20 => SDL_Scancode::SDL_SCANCODE_Q,
        21 => SDL_Scancode::SDL_SCANCODE_R,
        22 => SDL_Scancode::SDL_SCANCODE_S,
        23 => SDL_Scancode::SDL_SCANCODE_T,
        24 => SDL_Scancode::SDL_SCANCODE_U,
        25 => SDL_Scancode::SDL_SCANCODE_V,
        26 => SDL_Scancode::SDL_SCANCODE_W,
        27 => SDL_Scancode::SDL_SCANCODE_X,
        28 => SDL_Scancode::SDL_SCANCODE_Y,
        29 => SDL_Scancode::SDL_SCANCODE_Z,
        30 => SDL_Scancode::SDL_SCANCODE_1,
        31 => SDL_Scancode::SDL_SCANCODE_2,
        32 => SDL_Scancode::SDL_SCANCODE_3,
        33 => SDL_Scancode::SDL_SCANCODE_4,
        34 => SDL_Scancode::SDL_SCANCODE_5,
        35 => SDL_Scancode::SDL_SCANCODE_6,
        36 => SDL_Scancode::SDL_SCANCODE_7,
        37 => SDL_Scancode::SDL_SCANCODE_8,
        38 => SDL_Scancode::SDL_SCANCODE_9,
        39 => SDL_Scancode::SDL_SCANCODE_0,
        40 => SDL_Scancode::SDL_SCANCODE_RETURN,
        41 => SDL_Scancode::SDL_SCANCODE_ESCAPE,
        42 => SDL_Scancode::SDL_SCANCODE_BACKSPACE,
        43 => SDL_Scancode::SDL_SCANCODE_TAB,
        44 => SDL_Scancode::SDL_SCANCODE_SPACE,
        45 => SDL_Scancode::SDL_SCANCODE_MINUS,
        46 => SDL_Scancode::SDL_SCANCODE_EQUALS,
        47 => SDL_Scancode::SDL_SCANCODE_LEFTBRACKET,
        48 => SDL_Scancode::SDL_SCANCODE_RIGHTBRACKET,
        49 => SDL_Scancode::SDL_SCANCODE_BACKSLASH,
        50 => SDL_Scancode::SDL_SCANCODE_NONUSHASH,
        51 => SDL_Scancode::SDL_SCANCODE_SEMICOLON,
        52 => SDL_Scancode::SDL_SCANCODE_APOSTROPHE,
        53 => SDL_Scancode::SDL_SCANCODE_GRAVE,
        54 => SDL_Scancode::SDL_SCANCODE_COMMA,
        55 => SDL_Scancode::SDL_SCANCODE_PERIOD,
        56 => SDL_Scancode::SDL_SCANCODE_SLASH,
        57 => SDL_Scancode::SDL_SCANCODE_CAPSLOCK,
        58 => SDL_Scancode::SDL_SCANCODE_F1,
        59 => SDL_Scancode::SDL_SCANCODE_F2,
        60 => SDL_Scancode::SDL_SCANCODE_F3,
        61 => SDL_Scancode::SDL_SCANCODE_F4,
        62 => SDL_Scancode::SDL_SCANCODE_F5,
        63 => SDL_Scancode::SDL_SCANCODE_F6,
        64 => SDL_Scancode::SDL_SCANCODE_F7,
        65 => SDL_Scancode::SDL_SCANCODE_F8,
        66 => SDL_Scancode::SDL_SCANCODE_F9,
        67 => SDL_Scancode::SDL_SCANCODE_F10,
        68 => SDL_Scancode::SDL_SCANCODE_F11,
        69 => SDL_Scancode::SDL_SCANCODE_F12,
        70 => SDL_Scancode::SDL_SCANCODE_PRINTSCREEN,
        71 => SDL_Scancode::SDL_SCANCODE_SCROLLLOCK,
        72 => SDL_Scancode::SDL_SCANCODE_PAUSE,
        73 => SDL_Scancode::SDL_SCANCODE_INSERT,
        74 => SDL_Scancode::SDL_SCANCODE_HOME,
        75 => SDL_Scancode::SDL_SCANCODE_PAGEUP,
        76 => SDL_Scancode::SDL_SCANCODE_DELETE,
        77 => SDL_Scancode::SDL_SCANCODE_END,
        78 => SDL_Scancode::SDL_SCANCODE_PAGEDOWN,
        79 => SDL_Scancode::SDL_SCANCODE_RIGHT,
        80 => SDL_Scancode::SDL_SCANCODE_LEFT,
        81 => SDL_Scancode::SDL_SCANCODE_DOWN,
        82 => SDL_Scancode::SDL_SCANCODE_UP,
        83 => SDL_Scancode::SDL_SCANCODE_NUMLOCKCLEAR,
        84 => SDL_Scancode::SDL_SCANCODE_KP_DIVIDE,
        85 => SDL_Scancode::SDL_SCANCODE_KP_MULTIPLY,
        86 => SDL_Scancode::SDL_SCANCODE_KP_MINUS,
        87 => SDL_Scancode::SDL_SCANCODE_KP_PLUS,
        88 => SDL_Scancode::SDL_SCANCODE_KP_ENTER,
        89 => SDL_Scancode::SDL_SCANCODE_KP_1,
        90 => SDL_Scancode::SDL_SCANCODE_KP_2,
        91 => SDL_Scancode::SDL_SCANCODE_KP_3,
        92 => SDL_Scancode::SDL_SCANCODE_KP_4,
        93 => SDL_Scancode::SDL_SCANCODE_KP_5,
        94 => SDL_Scancode::SDL_SCANCODE_KP_6,
        95 => SDL_Scancode::SDL_SCANCODE_KP_7,
        96 => SDL_Scancode::SDL_SCANCODE_KP_8,
        97 => SDL_Scancode::SDL_SCANCODE_KP_9,
        98 => SDL_Scancode::SDL_SCANCODE_KP_0,
        99 => SDL_Scancode::SDL_SCANCODE_KP_PERIOD,
        100 => SDL_Scancode::SDL_SCANCODE_NONUSBACKSLASH,
        101 => SDL_Scancode::SDL_SCANCODE_APPLICATION,
        102 => SDL_Scancode::SDL_SCANCODE_POWER,
        103 => SDL_Scancode::SDL_SCANCODE_KP_EQUALS,
        104 => SDL_Scancode::SDL_SCANCODE_F13,
        105 => SDL_Scancode::SDL_SCANCODE_F14,
        106 => SDL_Scancode::SDL_SCANCODE_F15,
        107 => SDL_Scancode::SDL_SCANCODE_F16,
        108 => SDL_Scancode::SDL_SCANCODE_F17,
        109 => SDL_Scancode::SDL_SCANCODE_F18,
        110 => SDL_Scancode::SDL_SCANCODE_F19,
        111 => SDL_Scancode::SDL_SCANCODE_F20,
        112 => SDL_Scancode::SDL_SCANCODE_F21,
        113 => SDL_Scancode::SDL_SCANCODE_F22,
        114 => SDL_Scancode::SDL_SCANCODE_F23,
        115 => SDL_Scancode::SDL_SCANCODE_F24,
        116 => SDL_Scancode::SDL_SCANCODE_EXECUTE,
        117 => SDL_Scancode::SDL_SCANCODE_HELP,
        118 => SDL_Scancode::SDL_SCANCODE_MENU,
        119 => SDL_Scancode::SDL_SCANCODE_SELECT,
        120 => SDL_Scancode::SDL_SCANCODE_STOP,
        121 => SDL_Scancode::SDL_SCANCODE_AGAIN,
        122 => SDL_Scancode::SDL_SCANCODE_UNDO,
        123 => SDL_Scancode::SDL_SCANCODE_CUT,
        124 => SDL_Scancode::SDL_SCANCODE_COPY,
        125 => SDL_Scancode::SDL_SCANCODE_PASTE,
        126 => SDL_Scancode::SDL_SCANCODE_FIND,
        127 => SDL_Scancode::SDL_SCANCODE_MUTE,
        128 => SDL_Scancode::SDL_SCANCODE_VOLUMEUP,
        129 => SDL_Scancode::SDL_SCANCODE_VOLUMEDOWN,
        133 => SDL_Scancode::SDL_SCANCODE_KP_COMMA,
        134 => SDL_Scancode::SDL_SCANCODE_KP_EQUALSAS400,
        135 => SDL_Scancode::SDL_SCANCODE_INTERNATIONAL1,
        136 => SDL_Scancode::SDL_SCANCODE_INTERNATIONAL2,
        137 => SDL_Scancode::SDL_SCANCODE_INTERNATIONAL3,
        138 => SDL_Scancode::SDL_SCANCODE_INTERNATIONAL4,
        139 => SDL_Scancode::SDL_SCANCODE_INTERNATIONAL5,
        140 => SDL_Scancode::SDL_SCANCODE_INTERNATIONAL6,
        141 => SDL_Scancode::SDL_SCANCODE_INTERNATIONAL7,
        142 => SDL_Scancode::SDL_SCANCODE_INTERNATIONAL8,
        143 => SDL_Scancode::SDL_SCANCODE_INTERNATIONAL9,
        144 => SDL_Scancode::SDL_SCANCODE_LANG1,
        145 => SDL_Scancode::SDL_SCANCODE_LANG2,
        146 => SDL_Scancode::SDL_SCANCODE_LANG3,
        147 => SDL_Scancode::SDL_SCANCODE_LANG4,
        148 => SDL_Scancode::SDL_SCANCODE_LANG5,
        149 => SDL_Scancode::SDL_SCANCODE_LANG6,
        150 => SDL_Scancode::SDL_SCANCODE_LANG7,
        151 => SDL_Scancode::SDL_SCANCODE_LANG8,
        152 => SDL_Scancode::SDL_SCANCODE_LANG9,
        153 => SDL_Scancode::SDL_SCANCODE_ALTERASE,
        154 => SDL_Scancode::SDL_SCANCODE_SYSREQ,
        155 => SDL_Scancode::SDL_SCANCODE_CANCEL,
        156 => SDL_Scancode::SDL_SCANCODE_CLEAR,
        157 => SDL_Scancode::SDL_SCANCODE_PRIOR,
        158 => SDL_Scancode::SDL_SCANCODE_RETURN2,
        159 => SDL_Scancode::SDL_SCANCODE_SEPARATOR,
        160 => SDL_Scancode::SDL_SCANCODE_OUT,
        161 => SDL_Scancode::SDL_SCANCODE_OPER,
        162 => SDL_Scancode::SDL_SCANCODE_CLEARAGAIN,
        163 => SDL_Scancode::SDL_SCANCODE_CRSEL,
        164 => SDL_Scancode::SDL_SCANCODE_EXSEL,
        176 => SDL_Scancode::SDL_SCANCODE_KP_00,
        177 => SDL_Scancode::SDL_SCANCODE_KP_000,
        178 => SDL_Scancode::SDL_SCANCODE_THOUSANDSSEPARATOR,
        179 => SDL_Scancode::SDL_SCANCODE_DECIMALSEPARATOR,
        180 => SDL_Scancode::SDL_SCANCODE_CURRENCYUNIT,
        181 => SDL_Scancode::SDL_SCANCODE_CURRENCYSUBUNIT,
        182 => SDL_Scancode::SDL_SCANCODE_KP_LEFTPAREN,
        183 => SDL_Scancode::SDL_SCANCODE_KP_RIGHTPAREN,
        184 => SDL_Scancode::SDL_SCANCODE_KP_LEFTBRACE,
        185 => SDL_Scancode::SDL_SCANCODE_KP_RIGHTBRACE,
        186 => SDL_Scancode::SDL_SCANCODE_KP_TAB,
        187 => SDL_Scancode::SDL_SCANCODE_KP_BACKSPACE,
        188 => SDL_Scancode::SDL_SCANCODE_KP_A,
        189 => SDL_Scancode::SDL_SCANCODE_KP_B,
        190 => SDL_Scancode::SDL_SCANCODE_KP_C,
        191 => SDL_Scancode::SDL_SCANCODE_KP_D,
        192 => SDL_Scancode::SDL_SCANCODE_KP_E,
        193 => SDL_Scancode::SDL_SCANCODE_KP_F,
        194 => SDL_Scancode::SDL_SCANCODE_KP_XOR,
        195 => SDL_Scancode::SDL_SCANCODE_KP_POWER,
        196 => SDL_Scancode::SDL_SCANCODE_KP_PERCENT,
        197 => SDL_Scancode::SDL_SCANCODE_KP_LESS,
        198 => SDL_Scancode::SDL_SCANCODE_KP_GREATER,
        199 => SDL_Scancode::SDL_SCANCODE_KP_AMPERSAND,
        200 => SDL_Scancode::SDL_SCANCODE_KP_DBLAMPERSAND,
        201 => SDL_Scancode::SDL_SCANCODE_KP_VERTICALBAR,
        202 => SDL_Scancode::SDL_SCANCODE_KP_DBLVERTICALBAR,
        203 => SDL_Scancode::SDL_SCANCODE_KP_COLON,
        204 => SDL_Scancode::SDL_SCANCODE_KP_HASH,
        205 => SDL_Scancode::SDL_SCANCODE_KP_SPACE,
        206 => SDL_Scancode::SDL_SCANCODE_KP_AT,
        207 => SDL_Scancode::SDL_SCANCODE_KP_EXCLAM,
        208 => SDL_Scancode::SDL_SCANCODE_KP_MEMSTORE,
        209 => SDL_Scancode::SDL_SCANCODE_KP_MEMRECALL,
        210 => SDL_Scancode::SDL_SCANCODE_KP_MEMCLEAR,
        211 => SDL_Scancode::SDL_SCANCODE_KP_MEMADD,
        212 => SDL_Scancode::SDL_SCANCODE_KP_MEMSUBTRACT,
        213 => SDL_Scancode::SDL_SCANCODE_KP_MEMMULTIPLY,
        214 => SDL_Scancode::SDL_SCANCODE_KP_MEMDIVIDE,
        215 => SDL_Scancode::SDL_SCANCODE_KP_PLUSMINUS,
        216 => SDL_Scancode::SDL_SCANCODE_KP_CLEAR,
        217 => SDL_Scancode::SDL_SCANCODE_KP_CLEARENTRY,
        218 => SDL_Scancode::SDL_SCANCODE_KP_BINARY,
        219 => SDL_Scancode::SDL_SCANCODE_KP_OCTAL,
        220 => SDL_Scancode::SDL_SCANCODE_KP_DECIMAL,
        221 => SDL_Scancode::SDL_SCANCODE_KP_HEXADECIMAL,
        224 => SDL_Scancode::SDL_SCANCODE_LCTRL,
        225 => SDL_Scancode::SDL_SCANCODE_LSHIFT,
        226 => SDL_Scancode::SDL_SCANCODE_LALT,
        227 => SDL_Scancode::SDL_SCANCODE_LGUI,
        228 => SDL_Scancode::SDL_SCANCODE_RCTRL,
        229 => SDL_Scancode::SDL_SCANCODE_RSHIFT,
        230 => SDL_Scancode::SDL_SCANCODE_RALT,
        231 => SDL_Scancode::SDL_SCANCODE_RGUI,
        257 => SDL_Scancode::SDL_SCANCODE_MODE,
        258 => SDL_Scancode::SDL_SCANCODE_AUDIONEXT,
        259 => SDL_Scancode::SDL_SCANCODE_AUDIOPREV,
        260 => SDL_Scancode::SDL_SCANCODE_AUDIOSTOP,
        261 => SDL_Scancode::SDL_SCANCODE_AUDIOPLAY,
        262 => SDL_Scancode::SDL_SCANCODE_AUDIOMUTE,
        263 => SDL_Scancode::SDL_SCANCODE_MEDIASELECT,
        264 => SDL_Scancode::SDL_SCANCODE_WWW,
        265 => SDL_Scancode::SDL_SCANCODE_MAIL,
        266 => SDL_Scancode::SDL_SCANCODE_CALCULATOR,
        267 => SDL_Scancode::SDL_SCANCODE_COMPUTER,
        268 => SDL_Scancode::SDL_SCANCODE_AC_SEARCH,
        269 => SDL_Scancode::SDL_SCANCODE_AC_HOME,
        270 => SDL_Scancode::SDL_SCANCODE_AC_BACK,
        271 => SDL_Scancode::SDL_SCANCODE_AC_FORWARD,
        272 => SDL_Scancode::SDL_SCANCODE_AC_STOP,
        273 => SDL_Scancode::SDL_SCANCODE_AC_REFRESH,
        274 => SDL_Scancode::SDL_SCANCODE_AC_BOOKMARKS,
        275 => SDL_Scancode::SDL_SCANCODE_BRIGHTNESSDOWN,
        276 => SDL_Scancode::SDL_SCANCODE_BRIGHTNESSUP,
        277 => SDL_Scancode::SDL_SCANCODE_DISPLAYSWITCH,
        278 => SDL_Scancode::SDL_SCANCODE_KBDILLUMTOGGLE,
        279 => SDL_Scancode::SDL_SCANCODE_KBDILLUMDOWN,
        280 => SDL_Scancode::SDL_SCANCODE_KBDILLUMUP,
        281 => SDL_Scancode::SDL_SCANCODE_EJECT,
        282 => SDL_Scancode::SDL_SCANCODE_SLEEP,
        283 => SDL_Scancode::SDL_SCANCODE_APP1,
        284 => SDL_Scancode::SDL_SCANCODE_APP2,
        285 => SDL_Scancode::SDL_SCANCODE_AUDIOREWIND,
        286 => SDL_Scancode::SDL_SCANCODE_AUDIOFASTFORWARD,
        _ => SDL_Scancode::SDL_SCANCODE_UNKNOWN,
    }
}

pub fn is_unknwon(scancode: SDL_Scancode) -> bool {
    match scancode {
        SDL_Scancode::SDL_SCANCODE_UNKNOWN => true,
        _ => false,
    }
}

pub fn is_unknown_keycode_u32(scancode: u32) -> bool {
    scancode == SDL_KeyCode::SDLK_UNKNOWN as u32
}

pub fn is_unknown_scancode_u32(scancode: u32) -> bool {
    scancode == SDL_Scancode::SDL_SCANCODE_UNKNOWN as u32
}

pub fn map_key_code_to_scancode_cursed(code: u32) -> SDL_Scancode {
    if is_unknown_keycode_u32(code) {
        return SDL_Scancode::SDL_SCANCODE_UNKNOWN;
    }
    let keycode: SDL_KeyCode = unsafe {
        transmute(code) 
    };
    let scancode_enum = map_keycode_to_scancode(keycode);
    scancode_enum
}

pub fn map_key_code_to_scancode_cursed_u32(code: u32) -> u32 {
    map_key_code_to_scancode_cursed(code) as u32
}