[package]
name = "hyperwarp"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redhook = "2.0"
libc = "0.2"

[lib]
name = "hyperwarphooker"
crate_type = ["dylib"]