# adapted from ms devcontainers
FROM 1-bullseye

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
     && apt-get -y install --no-install-recommends neofetch curl htop nano python3 nodejs
