[package]
name = "stellar_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "=1.3.3"
lazy_static = "1.4.0"
serde = { version = "1.0.203", features = ["derive"] }
strum = "0.26.2"
strum_macros = "0.26.3"
serde_repr = "0.1"
serde_json = "1.0"